import { Item, Category } from './types';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item-101',
    type: 'lost',
    title: 'Black Leather Bi-fold Wallet',
    description: "Black Tommy Hilfiger leather wallet with silver crest badge. Contains driver's license, student ID, and metro card.",
    category: 'Wallet',
    location: 'Library 2nd Floor Study Cubicle #14',
    date: '2025-05-12',
    name: 'Marcus Vance',
    email: 'marcus.v@campus.edu',
    phone: '+1 (555) 234-8901',
    status: 'active',
    postedAt: '2025-05-12T14:30:00.000Z',
  },
  {
    id: 'item-102',
    type: 'found',
    title: 'Apple iPhone 14 Pro (Deep Purple)',
    description: 'Found with clear MagSafe case and a sticker of a golden retriever on the back. Locked with PIN screen.',
    category: 'Phone',
    location: 'Hospital Cafeteria East Wing Booth',
    date: '2025-05-13',
    name: 'Nurse Elena Reyes',
    email: 'elena.reyes@metrohealth.org',
    phone: '+1 (555) 987-6543',
    status: 'active',
    postedAt: '2025-05-13T09:15:00.000Z',
  },
  {
    id: 'item-103',
    type: 'found',
    title: 'Subaru Car Key with Navy Lanyard',
    description: 'Key fob with blue silicone cover and a university lanyard with small metal whistle attached.',
    category: 'Keys',
    location: 'North Parking Lot Gate B Bench',
    date: '2025-05-11',
    name: 'Officer David Kim',
    email: 'security@citycenter.org',
    phone: '+1 (555) 345-6712',
    status: 'active',
    postedAt: '2025-05-11T17:45:00.000Z',
  },
  {
    id: 'item-104',
    type: 'lost',
    title: 'Navy Herschel Little America Backpack',
    description: 'Navy blue canvas with tan faux-leather straps. Left near Lecture Hall 301 after morning physics session.',
    category: 'Bag',
    location: 'Science Building Room 301 Hallway',
    date: '2025-05-10',
    name: 'Sophia Lin',
    email: 'sophia.l@univ.edu',
    phone: '+1 (555) 456-7890',
    status: 'active',
    postedAt: '2025-05-10T11:20:00.000Z',
  },
  {
    id: 'item-105',
    type: 'found',
    title: 'Silver Tommy Hilfiger Mens Wallet',
    description: 'Dark leather bi-fold wallet turned into circulation desk. Contains student ID card for M. Vance and transit pass.',
    category: 'Wallet',
    location: 'Campus Main Library Front Checkout Desk',
    date: '2025-05-12',
    name: 'Sarah Chen (Librarian)',
    email: 'library-lost@campus.edu',
    phone: '+1 (555) 890-4421',
    status: 'active',
    postedAt: '2025-05-12T16:05:00.000Z',
  },
  {
    id: 'item-106',
    type: 'lost',
    title: 'Purple iPhone 14 Pro Max 256GB',
    description: 'Deep purple iPhone with clear case and pet puppy sticker on rear. Dropped near hospital outpatient clinic.',
    category: 'Phone',
    location: 'Memorial Hospital Outpatient Clinic Entrance',
    date: '2025-05-13',
    name: 'Carlos Mendez',
    email: 'carlos.m@freemail.com',
    phone: '+1 (555) 612-9988',
    status: 'active',
    postedAt: '2025-05-13T08:50:00.000Z',
  },
  {
    id: 'item-107',
    type: 'found',
    title: 'Blue Herschel Backpack with Notebooks',
    description: 'Navy blue Herschel backpack with tan leather buckles. Found on chair outside Lecture Hall 301. Contains physics binder.',
    category: 'Bag',
    location: 'Science Hall Custodial Lost & Found',
    date: '2025-05-10',
    name: 'Custodial Services Office',
    email: 'facilities@univ.edu',
    phone: '+1 (555) 234-7711',
    status: 'active',
    postedAt: '2025-05-10T14:10:00.000Z',
  },
  {
    id: 'item-108',
    type: 'lost',
    title: 'Subaru Key Fob with Whistle',
    description: 'Lost set of keys with blue rubber case and campus lanyard with silver emergency whistle.',
    category: 'Keys',
    location: 'North Parking Lot walkway towards Gate B',
    date: '2025-05-11',
    name: 'Emily Watson',
    email: 'emily.w@domain.com',
    phone: '+1 (555) 789-2234',
    status: 'active',
    postedAt: '2025-05-11T16:30:00.000Z',
  },
];

export const CATEGORIES: Category[] = [
  'Wallet',
  'Phone',
  'Keys',
  'Bag',
  'Laptop',
  'ID Card',
  'Clothing',
  'Electronics',
  'Other',
];
